---
output:
  pdf_document:
    latex_engine: xelatex
classoption: landscape
geometry: margin=1cm
mainfont: Arial Narrow
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \fontsize{12}{22}
- \fontseries{b}
- \selectfont
- \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = FALSE, message = FALSE, warning = FALSE, error = FALSE)
# output:
#   pdf_document:
#     latex_engine: xelatex
```

```{r write_caption}

vess <- text_list(x = paste0("F/V \\textit{",
                             unique(gsub(pattern = "F/V ", replacement = "", fixed = TRUE, 
                                         x = dat$vessel_name[!is.na(dat$vessel_name)])),"}"))

surveys <- gsub(pattern = "Eastern", 
                replacement = "eastern", 
                x = unique(dat_plot$survey))
surveys <- gsub(pattern = "Northern", 
                replacement = "northern", 
                x = surveys)
SRVYs <- unique(dat_plot$SRVY)


# find regions in west to east
if (SRVY %in% c("AI", "GOA")) {
  goaai_regions <- shp$survey.grid %>% 
    st_centroid() %>% 
    st_transform(crs = "+proj=longlat +datum=WGS84") %>%
    st_coordinates() %>% 
    data.frame() %>%
    dplyr::mutate(area_name = unlist(shp$survey.grid$area_name)) %>% 
    dplyr::group_by(area_name) %>% 
    dplyr::summarise(minlon = min(X, na.rm = TRUE)) %>% 
    dplyr::arrange(minlon)
  
  goaai_regions0 <- paste0("This survey covers the ", 
                           text_list(goaai_regions$area_name), 
                           " districts. ")
  goaai_regions <- paste0("This survey covers the ", 
                          text_list(goaai_regions$area_name), 
                          " districts, which are sampled randomly each year. ")
} else {
  goaai_regions <- ""
}

intro0 <- paste0(
  "NOAA Fisheries AFSC Groundfish Assessment Program conducted the ", 
  text_list(surveys),
  " bottom trawl survey",
  ifelse(length(surveys)>1, "s", ""), ". ")

intro_vess <- paste0(
  "NOAA Fisheries AFSC Groundfish Assessment Program conducted the ", 
  text_list(surveys),
  " bottom trawl survey",
  ifelse(length(surveys)>1, "s", "")
  ," in ", maxyr, 
  " aboard the ",
  vess,
  ". ", 
  goaai_regions)

foss_not <- paste0("The final, validated haul and catch data will be publicly accessible on Fisheries One Stop Shop data platform (\\textit{https://www.fisheries.noaa.gov/foss}) after the survey is complete. ")
foss_avail <- paste0("These data are publicly accessible on Fisheries One Stop Shop data platform (\\textit{https://www.fisheries.noaa.gov/foss}",ifelse(file_end %in% c("mean", "mean_cb"), "and the coldpool R package (\\textit{https://github.com/afsc-gap-products/coldpool}", ""),"). ")
foss0 <- ifelse(data_source == "gd", foss_not, foss_avail)

if (file_end %in% c("mean", "mean_cb")) {  
  temp <- gsub(pattern = "[a-zA-Z]+", replacement = "", x = plot_subtitle)
  temp <- strsplit(x = trimws(temp), split = " \n ")[[1]]
  temp <- gsub(pattern = " )", replacement = " years)", x = temp)
  temp <- trimws(temp)
  temp <- gsub(pattern = " (", replacement = "; ", x = temp,fixed = TRUE)
  temp <- paste0(surveys, " (", temp)
  
  temp <- paste0(
    "The time series mean ",
    tolower(var00), 
    "s from the NOAA Fisheries ", 
    text_list(temp), 
    " bottom trawl survey", 
    ifelse(length(surveys)>1, "s", ""),
    ". ")  
  
  fig_cap <- paste0(
    temp, 
    # stringr::str_to_sentence(plot_title), "s in the ", 
    #              gsub(x = plot_subtitle, pattern = "\n", replacement = " "), ". ", 
    foss_avail)
  
} else if (file_end %in% c("anom", "anom_cb")) {
  
  temp <- gsub(pattern = "[a-zA-Z]+", replacement = "", x = plot_subtitle)
  temp <- strsplit(x = trimws(temp), split = " \n ")[[1]]
  temp <- gsub(pattern = " )", replacement = " years)", x = temp)
  temp <- trimws(temp)
  temp <- gsub(pattern = " (", replacement = "; ", x = temp,fixed = TRUE)
  temp <- paste0(surveys, " (", temp)
  
  temp <- paste0(
    "The time series mean ",
    tolower(var00), 
    "s from the ", 
    text_list(temp), 
    " bottom trawl survey", 
    ifelse(length(surveys)>1, "s are", " is"), 
    " compared to ",
    ifelse(length(surveys)>1, 
           paste0("their respective ", maxyr, " surveys"), 
           paste0("the ", maxyr, " survey")),
    " (", 
    ifelse(min(as.Date(dat$date), na.rm = TRUE) == max_date, 
           paste0("on ", format_date_txt(x = min(as.Date(dat$date), na.rm = TRUE), "%B %d %Y")), 
           paste0(format_date_txt(x = min(as.Date(dat$date), na.rm = TRUE), "%B %d"), 
                  "-", 
                  format_date_txt(x = as.Date(max_date), "%B %d"))),
    "). "
  )
  
  fig_cap <- paste0(
    
    "The ", maxyr,
    " near real-time ocean bottom temperature anomaly in the NOAA Fisheries AFSC Groundfish Assessment Program's ",
    text_list(surveys),
    " bottom trawl survey",
    ifelse(length(surveys)>1, "s", ""),
    ". ",
    temp, 
    foss0)
  
} else if (file_end == "grid") { # (as.character(dates0[1]) == "none") {
  
  if (SRVY %in% c("BS", "NBS", "EBS")) {
    fig_cap <- paste0( "Map of the ", text_list(surveys)," ",maxyr," survey stations and the ", 
      text_list(x = paste0(unique(shp$bathymetry$meters), " m")),
      " bathymetry lines. ")
  } else if (SRVY %in% c("GOA", "AI")) {
    fig_cap <- paste0(
      "The ", surveys, " bottom trawl survey. ", 
      goaai_regions0)
  }
  
} else if (file_end %in% c("daily", "daily_cb")) {
  
  # Find what stations were sampled on this day
  loc <- dat_plot %>% 
    dplyr::filter(!is.na(var) & 
                    date == max_date) 
  
  stations_first_last <- ""
  if (firstplotofrun) {
    stations_first_last <- "This is the first day of the survey. "
    # } else if (date_entered[length(date_entered)] == max_date & sum(is.na(dat_plot$var))>0) {
  } else if (lastdayofsurvey & 
             SRVY %in% c("BS", "EBS", "NBS")) {
    stations_first_last <- "This is the last day of the survey. "
  } 
  
  if (nrow(loc) == 0) {
    stations1 <- paste0("No stations were sampled on ", format_date_txt(x = as.Date(max_date)),". ")
  } else {
    
    dat_max_date <- grid_stations_plot %>% 
      sf::st_cast("MULTIPOLYGON") %>% 
      sf::st_centroid()  %>% 
      sf::st_transform(x = ., crs = "+proj=longlat +datum=WGS84")%>%
      sf::st_coordinates() %>%
      data.frame() %>% 
      dplyr::rename(lon = X, 
                    lat = Y) %>% 
      dplyr::mutate(
        station = grid_stations_plot$station, 
        stratum = grid_stations_plot$stratum, 
        stratum = as.character(stratum)) %>%
      dplyr::left_join(y = ., 
                       x = loc %>% 
                         dplyr::mutate(stratum = as.character(stratum)) %>% 
                         dplyr::select(stratum, station, vessel_shape, vessel_name, date, var_bin), 
                       by = c("stratum", "station"))  %>%
      dplyr::arrange(vessel_shape) %>% 
      dplyr::mutate(lon = round(x = lon, digits = 2), 
                    lat = round(x = lat, digits = 2)) %>% 
      dplyr::filter(!is.na(lon))
    
    temp <- c()
    for (iii in 1:length(unique(dat_max_date$vessel_shape))) {
      surveys <- dat_max_date[which(dat_max_date$vessel_shape == unique(dat_max_date$vessel_shape)[iii]),]
      temp <- c(temp, 
                paste0(
                  ifelse(nrow(surveys)>1, "", "a "), "station", 
                  ifelse(nrow(surveys)>1, "s", ""), " ", 
                  text_list(x = 
                              paste0(surveys$station,
                                     " (",surveys$lat,"°N, ",surveys$lon,"°W; ",
                                     gsub(pattern = " ", 
                                          replacement = "", 
                                          x = surveys$var_bin, fixed = TRUE),"°C)")), 
                  " ", ifelse(nrow(surveys)>1, "were", "was"), " surveyed by the F/V \\textit{",
                  gsub(pattern = "F/V ", 
                       replacement = "", 
                       fixed = TRUE,
                       x = unique(surveys$vessel_name[!is.na(surveys$vessel_name)])),"}") )
    }
    
    temp1 <- ""
    temp11 <- as.character(unique(dat_survey$vessel_shape)); temp11 <- temp11[!is.na(temp11)] # vessels in data
    temp12 <- as.character(unique(dat_max_date$vessel_shape)) # vessels from maxdate
    temp13 <- setdiff(temp11, temp12); temp13 <- temp13[!is.na(temp13)]
    if (length(temp13)>0) {
      temp1 <- paste0("No stations were surveyed by the F/V \\textit{", 
                      gsub(pattern = "F/V ", 
                           replacement = "", 
                           fixed = TRUE,
                           x = setdiff(unique(dat_plot$vessel_name[!is.na(dat_plot$vessel_name)]), 
                                       unique(dat_max_date$vessel_name))), 
                      "}. ")
      temp1 <- ifelse(grepl(pattern = "No stations were surveyed by the F/V \\textit{}. ", 
                            x = temp1, fixed = TRUE), 
                      "", 
                      temp1)
    }
    stations1 <- paste0("On ", format_date_txt(as.Date(max_date)), ", ",
                        text_list(temp), ". ", temp1)
  }
  
  # Are stations planned for the next day?
  if (show_planned_stations) {
    # if (!is.null(dat_planned) & length(dat_planned) == 0) {
    #         stations1 <- paste0(stations1, "There are no stations planned for ", 
    #                             format_date_txt(x = (as.Date(max_date)+1)), ". ")
    #   } 
    
    if (!lastdayofsurvey) {
      temp <- nrow(dat_planned[dat_planned$planned == "Y",])
      stations1 <- 
        paste0(stations1, "There are ",
               ifelse(temp == 0, "no", temp),
               " stations planned for ", 
               format_date_txt(x = (as.Date(max_date)+1)), ". ")
    }
  } else if (SRVY %in% c("GOA", "AI") &
             !(date_entered[length(date_entered)] == max_date & sum(is.na(dat_plot$var))>0)) { # not the last day of the survey
    stations1 <- paste0(stations1, "Stations yet to be sampled are shown as gray dots. ")
  }
  
  
  
  temp00 <- paste0("The near real-time ocean bottom temperatures depicted were collected ", 
                    ifelse(min(as.Date(dat$date), na.rm = TRUE) == max_date, 
                           paste0("on ", format_date_txt(x = min(as.Date(dat$date)+
                                                                   ifelse(show_planned_stations, 1, 0), 
                                                                 na.rm = TRUE), "%B %d, %Y")), 
                           paste0(format_date_txt(x = min(as.Date(dat$date)+ifelse(show_planned_stations, 1, 0), 
                                                          na.rm = TRUE), "%B %d"), 
                                  "-", 
                                  format_date_txt(x = as.Date(max_date), "%B %d"))), ". ")
    temp01 <- paste0("The near real-time ocean bottom temperatures depicted were collected on ",
                     format_date_txt(x = min(as.Date(dat$date)+ifelse(show_planned_stations, 1, 0), 
                                             na.rm = TRUE), "%B %d, %Y"),
                     ". ")
  
  fig_cap <- paste0(ifelse(grepl(pattern = "F/V", x = stations1), intro0, intro_vess), 
                    ifelse(firstplotofrun, temp01, temp00), 
                    stations_first_last, 
                    stations1)
  
}

fig_alt <- fig_cap <- paste0(fig_cap, "\\textit{Credit: NOAA Fisheries}")

fig_alt <- gsub(pattern = "\\textit{", replacement = "", x = fig_alt, fixed = TRUE)
fig_alt <- gsub(pattern = "}", replacement = "", x = fig_alt, fixed = TRUE)
# fig_alt <- gsub(pattern = " (https://www.fisheries.noaa.gov/foss)",
#                 replacement = "", 
#                 x = fig_alt, 
#                 fixed = TRUE)

readr::write_lines(x = fig_alt, file = paste0(dir_out, filename0, ".txt"))

```

```{r plot-figure, fig.cap = fig_cap, fig.align = 'center', fig.width = 10.5, fig.height = 6.5, dpi = 320}
gg
```

